DROP TABLE IF EXISTS KANJI;
CREATE TABLE IF NOT EXISTS `KANJI` (
  `Symbol` varchar(5) NOT NULL,
  `OnSound` varchar(15) DEFAULT NULL,
  `KunSound` varchar(15) DEFAULT NULL,
  `Strokes` int(5) DEFAULT NULL,
  `Heisig` varchar(20) DEFAULT NULL,
  `KunRomaji` varchar(20) DEFAULT NULL,
  `OnRomaji` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`Symbol`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


INSERT INTO `KANJI` (`Symbol`, `OnSound`, `KunSound`, `Strokes`, `Heisig`, `KunRomaji`, `OnRomaji`) VALUES
('一', 'イチ', 'ひと', 1, 'one', 'hito', 'ichi'),
('右', 'ウ', 'みぎ', 5, 'right', 'migi', 'u'),
('雨', 'ウ', 'あめ', 8, 'rain', 'ame', 'u'),
('円', 'エン', 'まる', 4, 'circle', 'maru', 'en'),
('王', 'オウ', '', 4, 'king', '', 'ou'),
('音', 'オン', 'おと', 9, 'sound', 'oto', 'on'),
('下', 'カ', 'した', 3, 'below', 'shita', 'ka'),
('火', 'カ', 'ひ', 4, 'fire', 'hi', 'ka'),
('花', 'カ', 'はな', 7, 'flower', 'hana', 'ka'),
('学', 'ガク', 'まな', 8, 'study', 'mana', 'gaku'),
('気', 'キ', '', 6, 'spirit', '', 'ki'),
('九', 'キュウ', 'ここの', 2, 'nine', 'kokono', 'kyuu'),
('休', 'キュウ', 'やす', 6, 'rest', 'yasu', 'kyuu'),
('金', 'キン', 'かね', 8, 'gold', 'kane', 'kin'),
('空', 'クウ', 'そら', 8, 'empty', 'sora', 'kuu'),
('月', 'ゲツ', 'つき', 4, 'month', 'tsuki', 'getsu'),
('犬', 'ケン', 'いぬ', 4, 'dog', 'inu', 'ken'),
('見', 'ケン', 'み', 7, 'see', 'mi', 'ken'),
('五', 'ゴ', 'いつ', 4, 'five', 'itsu', 'go'),
('口', 'コウ', 'くち', 3, 'mouth', 'kuchi', 'kou'),
('校', 'コウ', '', 10, 'exam', '', 'kou'),
('左', 'サ', 'ひだり', 5, 'left', 'hidari', 'sa'),
('三', 'サン', 'み', 3, 'three', 'mi', 'san'),
('山', 'サン', 'やま', 3, 'mountain', 'yama', 'san'),
('子', 'シ', 'こ', 3, 'child', 'ko', 'shi'),
('四', 'シ', 'よん', 5, 'four', 'yon', 'shi'),
('糸', 'シ', 'いと', 6, 'thread', 'ito', 'shi'),
('字', 'ジ', 'あざ', 6, 'character', 'asa', 'ji'),
('耳', 'ジ', 'みみ', 6, 'ear', 'mimi', 'ji'),
('七', 'シチ', 'なな', 2, 'seven', 'nana', 'shichi'),
('車', 'シャ', 'くるま', 7, 'car', 'kuruma', 'sha'),
('手', 'シュ', 'て', 4, 'hand', 'te', 'shu'),
('十', 'ジュウ', 'とお', 2, 'ten', 'too', 'juu'),
('女', 'ジョ', 'おんな', 3, 'woman', 'onna', 'jo'),
('小', 'ショウ', 'こ-', 3, 'little', 'ko-', 'shou'),
('上', 'ジョウ', 'うえ', 3, 'above', 'ue', 'jou'),
('森', 'シン', 'もり', 12, 'forest', 'mori', 'shin'),
('人', 'ジン', 'ひと', 2, 'person', 'hito', 'jin'),
('水', 'スイ', 'みず', 4, 'water', 'mizu', 'sui'),
('正', 'セイ', 'まさ', 5, 'correct', 'masa', 'sei'),
('生', 'セイ', 'なま', 5, 'life', 'nama', 'sei'),
('青', 'セイ', 'あお', 8, 'blue', 'ao', 'sei'),
('夕', 'セキ', 'ゆう', 3, 'evening', 'yuu', 'seki'),
('石', 'セキ', 'いし', 5, 'stone', 'ishi', 'seki'),
('赤', 'セキ', 'あか', 7, 'red', 'aka', 'seki'),
('千', 'セン', 'ち', 3, 'thousand', 'chi', 'sen'),
('川', 'セン', 'かわ', 3, 'stream', 'kawa', 'sen'),
('先', 'セン', 'さき', 6, 'before', 'saki', 'sen'),
('早', 'ソウ', 'はや', 6, 'early', 'haya', 'sou'),
('足', 'ソク', 'あし', 7, 'leg', 'ashi', 'soku'),
('村', 'ソン', 'むら', 7, 'town', 'mura', 'son'),
('大', 'ダイ', 'おお', 3, 'large', 'oo', 'dai'),
('男', 'ダン', 'おとこ', 7, 'man', 'otoko', 'dan'),
('中', 'チュウ', 'なか', 4, 'in', 'naka', 'chuu'),
('虫', 'チュウ', 'むし', 6, 'insect', 'mushi', 'chuu'),
('町', 'チョウ', 'まち', 7, 'village', 'machi', 'chou'),
('天', 'テン', 'あま-', 4, 'heavens', 'ama', 'ten'),
('田', 'デン', 'た', 5, 'rice field', 'ta', 'den'),
('土', 'ド', 'つち', 3, 'soil', 'tsuchi', 'do'),
('二', 'ニ', 'ふた', 2, 'two', 'futa', 'ni'),
('日', 'ニチ', 'ひ', 4, 'day', 'hi', 'nichi'),
('入', 'ニュウ', 'はい', 2, 'enter', 'hai', 'nyuu'),
('年', 'ネン', 'とし', 6, 'year', 'toshi', 'nen'),
('白', 'ハク', 'しろ', 5, 'white', 'shiro', 'haku'),
('八', 'ハチ', 'や', 2, 'eight', 'ya', 'hachi'),
('百', 'ヒャク', 'もも', 6, 'hundred', 'momo', 'hyaku'),
('文', 'ブン', 'ふみ', 4, 'sentence', 'fumi', 'bun'),
('木', 'ボク', 'き', 4, 'tree', 'ki', 'boku'),
('本', 'ホン', 'もと', 5, 'book', 'moto', 'hon'),
('出', 'シュツ', 'で', 5, 'exit', 'de', 'shutsu'),
('名', 'メイ', 'な', 6, 'name', 'na', 'mei'),
('目', 'モク', 'め', 5, 'eye', 'me', 'moku'),
('立', 'リツ', 'た', 5, 'stand up', 'ta', 'ritsu'),
('力', 'リョク', 'ちから', 2, 'power', 'chikara', 'ryoku'),
('林', 'リン', 'はやし', 8, 'grove', 'hayashi', 'rin'),
('六', 'ロク', 'む', 4, 'six', 'mu', 'roku'),
('草', 'ソウ', 'くさ', 9, 'grass', 'kusa', 'sou'),
('玉', 'ギョク', 'たま', 5, 'jewel', 'tama', 'gyoku'),
('竹', 'チク', 'たけ', 6, 'bamboo', 'tage', 'chiku'),
('貝', 'バイ', 'かい', 7, 'shellfish', 'kai', 'bai');

